package calculator.language.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder2;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  /*package*/ final ConceptDescriptor myConceptCalculator = createDescriptorForCalculator();
  /*package*/ final ConceptDescriptor myConceptInputField = createDescriptorForInputField();
  /*package*/ final ConceptDescriptor myConceptInputFieldReference = createDescriptorForInputFieldReference();
  /*package*/ final ConceptDescriptor myConceptOutputField = createDescriptorForOutputField();
  private final LanguageConceptSwitch myIndexSwitch;

  public StructureAspectDescriptor() {
    myIndexSwitch = new LanguageConceptSwitch();
  }


  @Override
  public void reportDependencies(jetbrains.mps.smodel.runtime.StructureAspectDescriptor.Dependencies deps) {
    deps.extendedLanguage(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, "jetbrains.mps.lang.core");
    deps.extendedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
    deps.aggregatedLanguage(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, "jetbrains.mps.baseLanguage");
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptCalculator, myConceptInputField, myConceptInputFieldReference, myConceptOutputField);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    switch (myIndexSwitch.index(id)) {
      case LanguageConceptSwitch.Calculator:
        return myConceptCalculator;
      case LanguageConceptSwitch.InputField:
        return myConceptInputField;
      case LanguageConceptSwitch.InputFieldReference:
        return myConceptInputFieldReference;
      case LanguageConceptSwitch.OutputField:
        return myConceptOutputField;
      default:
        return null;
    }
  }


  /*package*/ int internalIndex(SAbstractConcept c) {
    return myIndexSwitch.index(c);
  }

  private static ConceptDescriptor createDescriptorForCalculator() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("calculator.language", "Calculator", 0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef0350a2L);
    b.class_(false, false, true);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.parent(0x4caf0310491e41f5L, 0x8a9b2006b3a94898L, 0x40c1a7cb987d20d5L);
    b.origin("r:65d38abe-56a4-447f-a178-64725d99f9a2(calculator.language.structure)/6968035171287388322");
    b.version(3);
    b.aggregate("inputField", 0x60b36f11ef03cf3fL).target(0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef03cf1fL).optional(true).ordered(true).multiple(true).origin("6968035171287420735").done();
    b.aggregate("outputField", 0x60b36f11ef03f8d9L).target(0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef03f8c5L).optional(true).ordered(true).multiple(true).origin("6968035171287431385").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("calculator.language", "InputField", 0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef03cf1fL);
    b.class_(false, false, false);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:65d38abe-56a4-447f-a178-64725d99f9a2(calculator.language.structure)/6968035171287420703");
    b.version(3);
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForInputFieldReference() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("calculator.language", "InputFieldReference", 0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef11392dL);
    b.class_(false, false, false);
    // extends: jetbrains.mps.baseLanguage.structure.Expression
    b.super_(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL);
    b.parent(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L);
    b.origin("r:65d38abe-56a4-447f-a178-64725d99f9a2(calculator.language.structure)/6968035171288299821");
    b.version(3);
    b.associate("field", 0x60b36f11ef11399dL).target(0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef03cf1fL).optional(false).origin("6968035171288299933").done();
    return b.create();
  }
  private static ConceptDescriptor createDescriptorForOutputField() {
    ConceptDescriptorBuilder2 b = new ConceptDescriptorBuilder2("calculator.language", "OutputField", 0x211ff9e735ad47f1L, 0x82c54fffdeb3d048L, 0x60b36f11ef03f8c5L);
    b.class_(false, false, false);
    b.origin("r:65d38abe-56a4-447f-a178-64725d99f9a2(calculator.language.structure)/6968035171287431365");
    b.version(3);
    b.aggregate("expression", 0x60b36f11ef04203aL).target(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL).optional(false).ordered(true).multiple(false).origin("6968035171287441466").done();
    return b.create();
  }
}
